---
 - name: Add extra repository
   apt_repository: repo="{{item}}"
   with_items:
     - "deb http://extras.ubuntu.com/ubuntu trusty main"
     - "deb-src http://extras.ubuntu.com/ubuntu trusty main"
   when: packaging_ubuntu_extras_repository

 - name: Add partner repository
   apt_repository: repo="{{item}}"
   with_items:
     - "deb http://archive.canonical.com/ubuntu trusty partner"
     - "deb-src http://archive.canonical.com/ubuntu trusty partner"
   when: packaging_ubuntu_partner_repository

 - name: Add multiverse repository
   apt_repository: repo="{{item}}"
   with_items:
     - "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
     - "deb-src http://archive.ubuntu.com/ubuntu/  trusty multiverse"
     - "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
     - "deb-src http://archive.ubuntu.com/ubuntu/  trusty-updates multiverse"
   when: packaging_ubuntu_multiverse_repository


